# Пользователь

## Создать пользователя (при наличии токена)
POST http://localhost:4000/users/register HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Iml2YW4uU2hpc2tpbkBtYWlsLmNvbSIsIm5hbWUiOiLQmNCy0LDQvSDQqNC40YjQutC40L0iLCJpZCI6IjY2NjUyZGUyODNiMDIyZmYxOTg0MjA3MiIsImlhdCI6MTcxNzkwOTU2NiwiZXhwIjoxNzE4MDgyMzY2fQ.Pr79zr1V1oJvIaWdLhg45QpFaOvx-H3ku6kBrJ25zA8
Content-Type: application/json

{
  "email": "h-oliver@mail.com",
  "name": "Oliver H",
  "type": "Ordinary",
  "avatar": "",
  "password": "gjjrjs45"
}

###

## Создать пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "defaultuser8@mail.com",
  "name": "default user 8",
  "type": "Ordinary",
  "password": "password"
}

###

## Создать пользователя (существующие пользователь)
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "jan.steen@example.com",
  "name": "Ян Стеен",
  "type": "Ordinary",
  "avatar": "https://images.app.goo.gl/iXNdWe3LEGUZpwg38",
  "password": "gjjrjs45"
}

###

## Авторизация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@gh.ru",
  "password": "999999"
}

###

## Авторизация пользователя (неверный пароль)

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "h-oliver@mail.com",
  "password": "gjjrjs5"
}

###

## Авторизация пользователя (неверный имейл)

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jan.steen@example.com",
  "password": "gjjrjs45"
}

###

## Проверить токен пользователя

GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imphbi5zdGVlbkBleGFtcGxlLmNvbSIsIm5hbWUiOiLQr9C9INCh0YLQtdC10L0iLCJpZCI6IjY2NDY0NWExMmUzYjBjYzZjODZiOTMwNyIsImlhdCI6MTcxODQzMzEyOCwiZXhwIjoxNzE4NjA1OTI4fQ.e3rJ1OkbhWvQ6Yx5wc9H_R4Zvf4VbBItpaWkM_r-hRU

###

## Проверить токен пользователя (неверный токен)

GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imgtb2xpdmVyQG1haWwuY29tIiwibmFtZSI6Ik9saXZlciBIIiwiaWQiOiI2NjY1ZjkzNzk1NGRkYTM3NGE3ZmJiNmMiLCJpYXQiOjE3MTgzMDY3NTcsImV4cCI6MTcxODQ3OTU1N30.vz9CtjpVfctxc025KosP2B6iZma2CoGGoBB9EmLK5Mo

###

## Проверить токен пользователя (токен отсутствует)

GET http://localhost:4000/users/login HTTP/1.1
###

## Поменять аватар

POST http://localhost:4000/users/666b4a0615792b273799aabe/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyNEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIiLCJpZCI6IjY2NmI0YTA2MTU3OTJiMjczNzk5YWFiZSIsImlhdCI6MTcxODQyOTQwMSwiZXhwIjoxNzE4NjAyMjAxfQ.6ba_EQAq5V1g-WPGutN5w896OBc4Zb9NRz1ixRVt4eI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\марина\Desktop\photo_2024-04-27_18-27-38.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
