# Предложения

## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

## Создать новое объявление
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Отель в историческом центре",
  "description": "Перкасный отель в историческом центре Брюсселя. Рядом все основые достопримечательности",
  "publicDate": "2023-01-08T06:24:40.283Z",
  "city": "Brussels",
  "previewImg": "preview.jpg",
  "photos": ["pic1.jpg", "pic2.jpg", "pic3.jpg", "pic4.jpg", "pic5.jpg", "pic6.jpg"],
  "isPremium": true,
  "rating": 1.45,
  "offerType": "room",
  "numberOfRooms": 3,
  "numberOfGuests": 6,
  "rentPrice": 32000,
  "features":[ "Breakfast", "Laptop friendly workspace"],
  "userId": "6329c3d6a04ab1061c6425ea",
  "numberOfComments": 0,
  "location": {
    "ln": 52.23452,
    "lt": 43.56739,
  },
}
