# Предложения

## Получить список предложений
GET http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json

###

## Создать новое объявление
POST http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Iml2YW4uU2hpc2tpbkBtYWlsLmNvbSIsIm5hbWUiOiLQmNCy0LDQvSDQqNC40YjQutC40L0iLCJpZCI6IjY2NjUyZGUyODNiMDIyZmYxOTg0MjA3MiIsImlhdCI6MTcxNzkwOTU2NiwiZXhwIjoxNzE4MDgyMzY2fQ.Pr79zr1V1oJvIaWdLhg45QpFaOvx-H3ku6kBrJ25zA8
Content-Type: application/json

{
  "title": "Отель в историческом центре",
  "description": "Перкасный отель в историческом центре Брюсселя. Рядом все основые достопримечательности",
  "publicDate": "2023-01-08T06:24:40.283Z",
  "city": "Brussels",
  "previewImg": "preview.jpg",
  "photos": ["pic1.jpg", "pic2.jpg", "pic3.jpg", "pic4.jpg", "pic5.jpg", "pic6.jpg"],
  "isPremium": true,
  "rating": 1.45,
  "offerType": "room",
  "numberOfRooms": 3,
  "numberOfGuests": 6,
  "rentPrice": 32000,
  "features": ["Baby seat", "Washer"],
  "numberOfComments": 0,
  "location": {
    "ln": "52.23452",
    "lt": "43.56739"
  }
}

###

## Получить детали объявления

GET http://localhost:4000/offers/664645a52e3b0cc6c86b993e/details HTTP/1.1
Content-Type: application/json

###

## Получить детали объявления авторизованный

GET http://localhost:4000/offers/664645b22e3b0cc6c86bb027/details HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Iml2YW4uU2hpc2tpbkBtYWlsLmNvbSIsIm5hbWUiOiLQmNCy0LDQvSDQqNC40YjQutC40L0iLCJpZCI6IjY2NjUyZGUyODNiMDIyZmYxOTg0MjA3MiIsImlhdCI6MTcxNzkwOTU2NiwiZXhwIjoxNzE4MDgyMzY2fQ.Pr79zr1V1oJvIaWdLhg45QpFaOvx-H3ku6kBrJ25zA8
Content-Type: application/json

###

## Изменить объявление

PATCH http://localhost:4000/offers/665af431fa15c77e6a0e503f/update HTTP/1.1
Content-Type: application/json

{
  "description": "Update Перкасный отель в историческом центре Брюсселя. Рядом все основые достопримечательности",
  "offerType": "hotel"
}

###

## Удаляет объявление

DELETE http://localhost:4000/offers/6665f7ed954dda374a7fbb69/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imgtb2xpdmVyQG1haWwuY29tIiwibmFtZSI6Ik9saXZlciBIIiwiaWQiOiI2NjY1ZjkzNzk1NGRkYTM3NGE3ZmJiNmMiLCJpYXQiOjE3MTc5NTg5ODMsImV4cCI6MTcxODEzMTc4M30.UywWDYpZ1iMjEi-2OYVOmDhlAjCLtC2nsd7k_z2E8pM
Content-Type: application/json
