# Предложения

## Получить список предложений
GET http://localhost:4000/offers/?limit=5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyQGdnLmdnIiwibmFtZSI6InJyIiwiaWQiOiI2NjZmZGFmOGJlZDk3NWM5Yjg5MmVjNmIiLCJpYXQiOjE3MTg4MjUyNjksImV4cCI6MTcxODk5ODA2OX0.F1AyjNvqRw5vGRrcbWn6-ilEwzzJEA5ASJ9RAkBPOCU
Content-Type: application/json

###

## Создать новое объявление
POST http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyOEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIgOCIsImlkIjoiNjY2ZjU0NDA0NzhmMzhjYTgyY2E5ZGVhIiwiaWF0IjoxNzE4NTcyNTEwLCJleHAiOjE3MTg3NDUzMTB9.4vLSmY5AJ_9AVFynuEzu90FHjFHbQ3WVuMdj1LcdyvY
Content-Type: application/json

{
  "title": "Отель в историческом центре",
  "description": "Перкасный отель в историческом центре Брюсселя. Рядом все основые достопримечательности",
  "publicDate": "2023-01-08T06:24:40.283Z",
  "city": "Brussels",
  "previewImg": "preview.jpg",
  "photos": ["pic1.jpg", "pic2.jpg", "pic3.jpg", "pic4.jpg", "pic5.jpg", "pic6.jpg"],
  "isPremium": true,
  "offerType": "room",
  "numberOfRooms": 3,
  "numberOfGuests": 6,
  "rentPrice": 32000,
  "features": ["Baby seat", "Washer"],
  "location": {
    "ln": "52.23452",
    "lt": "43.56739"
  }
}

###

## Получить детали объявления

GET http://localhost:4000/offers/666f3a825452ec71d7deed1e/details HTTP/1.1
Content-Type: application/json

###

## Получить детали объявления авторизованный

GET http://localhost:4000/offers/666f3a825452ec71d7deed1e/details HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyOEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIgOCIsImlkIjoiNjY2ZjU0NDA0NzhmMzhjYTgyY2E5ZGVhIiwiaWF0IjoxNzE4NTcyNTEwLCJleHAiOjE3MTg3NDUzMTB9.4vLSmY5AJ_9AVFynuEzu90FHjFHbQ3WVuMdj1LcdyvY
Content-Type: application/json

###

## Изменить объявление

PATCH http://localhost:4000/offers/666f59a694cdd4c101970aec/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyOEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIgOCIsImlkIjoiNjY2ZjU0NDA0NzhmMzhjYTgyY2E5ZGVhIiwiaWF0IjoxNzE4NTcyNTEwLCJleHAiOjE3MTg3NDUzMTB9.4vLSmY5AJ_9AVFynuEzu90FHjFHbQ3WVuMdj1LcdyvY
Content-Type: application/json

{
  "description": "Update Перкасный отель в историческом центре Брюсселя. Рядом все основые достопримечательности",
  "offerType": "hotel"
}

###

## Удаляет объявление

DELETE http://localhost:4000/offers/666f59a694cdd4c101970aec/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyOEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIgOCIsImlkIjoiNjY2ZjU0NDA0NzhmMzhjYTgyY2E5ZGVhIiwiaWF0IjoxNzE4NTcyNTEwLCJleHAiOjE3MTg3NDUzMTB9.4vLSmY5AJ_9AVFynuEzu90FHjFHbQ3WVuMdj1LcdyvY
Content-Type: application/json

###

## Добавляет объявление в избранное

PATCH http://localhost:4000/offers/666f3b3e302603e94f814213/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyQGdnLmdnIiwibmFtZSI6InJyIiwiaWQiOiI2NjZmZGFmOGJlZDk3NWM5Yjg5MmVjNmIiLCJpYXQiOjE3MTg4MjUyNjksImV4cCI6MTcxODk5ODA2OX0.F1AyjNvqRw5vGRrcbWn6-ilEwzzJEA5ASJ9RAkBPOCU
Content-Type: application/json

###

## Получить избранные у пользователя

GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyQGdnLmdnIiwibmFtZSI6InJyIiwiaWQiOiI2NjZmZGFmOGJlZDk3NWM5Yjg5MmVjNmIiLCJpYXQiOjE3MTg4MjUyNjksImV4cCI6MTcxODk5ODA2OX0.F1AyjNvqRw5vGRrcbWn6-ilEwzzJEA5ASJ9RAkBPOCU
Content-Type: application/json

###

## Получить премиум объявления

## Получить избранные у пользователя

GET http://localhost:4000/offers/Pas/premium HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRlZmF1bHR1c2VyOEBtYWlsLmNvbSIsIm5hbWUiOiJkZWZhdWx0IHVzZXIgOCIsImlkIjoiNjY2ZjU0NDA0NzhmMzhjYTgyY2E5ZGVhIiwiaWF0IjoxNzE4NTcyNTEwLCJleHAiOjE3MTg3NDUzMTB9.4vLSmY5AJ_9AVFynuEzu90FHjFHbQ3WVuMdj1LcdyvY
Content-Type: application/json
